"""
Video phase module for generating ManimGL animation code using KeywordsAI prompt management.

This module provides functionality to generate AI video animation scripts
that sync with narration audio using ManimGL (3Blue1Brown's animation engine).
"""

import os
from openai import OpenAI

# KeywordsAI Prompt ID for video generation
VIDEO_PROMPT_ID = "1d3fa979706a4912a99629f538edbcca"


def read_file(file_path: str) -> str:
    """
    Read a file's content.

    Args:
        file_path: Path to the file to read.

    Returns:
        The file content as a string.

    Raises:
        FileNotFoundError: If the file does not exist.
    """
    with open(file_path, "r") as f:
        return f.read()


def query_with_prompt(
    prompt_id: str,
    variables: dict[str, str] | None = None,
    model: str = "groq/openai/gpt-oss-120b",
    api_key: str | None = None,
    version: int | str | None = None,
) -> str:
    """
    Send a query using a KeywordsAI managed prompt.

    Args:
        prompt_id: The unique identifier of the saved prompt template in KeywordsAI.
        variables: Dictionary of variables to inject into the prompt template.
        model: The model identifier to use.
        api_key: KeywordsAI API key. Defaults to KEYWORDSAI_API_KEY_TEST env var.
        version: Optional prompt version. Omit for deployed version, use "latest"
                 for draft, or specify an integer for a specific version.

    Returns:
        The model's response text.

    Raises:
        openai.APIError: If the API request fails.
    """
    gateway = OpenAI(
        base_url="https://api.keywordsai.co/api/",
        api_key=api_key or os.getenv("KEYWORDSAI_API_KEY_TEST"),
    )

    prompt_config = {
        "prompt_id": prompt_id,
        "override": True,  # Use managed prompt instead of messages
    }
    if variables:
        prompt_config["variables"] = variables
    if version is not None:
        prompt_config["version"] = version

    response = gateway.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": ""}],  # Content comes from managed prompt
        extra_body={"prompt": prompt_config},
    )

    return response.choices[0].message.content


def generate_video_script(
    video_number: int,
    lesson_plan: str,
    video_template_path: str = "templates/gen_video_template.txt",
    audio_script_path: str = "ai_gen_audio.py",
    model: str = "groq/openai/gpt-oss-120b",
    api_key: str | None = None,
) -> str:
    """
    Generate an ai_gen_video.py script for a specific video's ManimGL animation.

    Uses the KeywordsAI managed prompt to create a Python script that
    generates ManimGL animations synchronized with the narration audio.

    Args:
        video_number: The video number to generate animation for.
        lesson_plan: The structured lesson plan content.
        video_template_path: Path to the gen_video_template.py file.
        audio_script_path: Path to the ai_gen_audio.py file (generated by audio_phase).
        model: The model identifier to use.
        api_key: KeywordsAI API key. Defaults to KEYWORDSAI_API_KEY_TEST env var.

    Returns:
        A Python script (ai_gen_video.py) that generates ManimGL animation for the video.
    """
    video_template_content = read_file(video_template_path)
    audio_script_content = read_file(audio_script_path)

    variables = {
        "AI_GEN_VIDEO_TEMPLATE_FILE": video_template_content,
        "AI_GEN_AUDIO_FILE": audio_script_content,
        "VIDEO_NUMBER": str(video_number),
        "THE_PLAN": lesson_plan,
    }

    return query_with_prompt(
        prompt_id=VIDEO_PROMPT_ID,
        variables=variables,
        model=model,
        api_key=api_key,
    )


if __name__ == "__main__":
    # Example usage
    example_plan = """
    Video 1: Introduction to Backtracking
    - Learning goal: Understand what backtracking is
    - Core ideas: Trial and error, systematic search, pruning
    """

    result = generate_video_script(
        video_number=1,
        lesson_plan=example_plan,
        video_template_path="templates/gen_video_template.txt",
        audio_script_path="3b1b_manimations/ai_gen_audio.py",
    )
    print(result)
